start cmd.exe /k "cd./venv/Scripts && activate && cd ..\.. && python -m Pyro4.naming"
start cmd.exe /k "cd./venv/Scripts && activate && cd ..\.. && python -m frontend"
start cmd.exe /k "cd./venv/Scripts && activate && cd ..\.. && python -m replica"
start cmd.exe /k "cd./venv/Scripts && activate && cd ..\.. && python -m replica"
start cmd.exe /k "cd./venv/Scripts && activate && cd ..\.. && python -m replica"